version: 2
updates:

  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` in the `root` directory
    directory: "/tools/2_validate_data"
    # Check the pip registry for updates every week
    schedule:
      interval: "weekly"

  # Enable version updates for github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
